/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Artist } from "./Artist";
import { ArtistCountArgs } from "./ArtistCountArgs";
import { ArtistFindManyArgs } from "./ArtistFindManyArgs";
import { ArtistFindUniqueArgs } from "./ArtistFindUniqueArgs";
import { CreateArtistArgs } from "./CreateArtistArgs";
import { UpdateArtistArgs } from "./UpdateArtistArgs";
import { DeleteArtistArgs } from "./DeleteArtistArgs";
import { AlbumFindManyArgs } from "../../album/base/AlbumFindManyArgs";
import { Album } from "../../album/base/Album";
import { TrackFindManyArgs } from "../../track/base/TrackFindManyArgs";
import { Track } from "../../track/base/Track";
import { ArtistService } from "../artist.service";
@graphql.Resolver(() => Artist)
export class ArtistResolverBase {
  constructor(protected readonly service: ArtistService) {}

  async _artistsMeta(
    @graphql.Args() args: ArtistCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Artist])
  async artists(@graphql.Args() args: ArtistFindManyArgs): Promise<Artist[]> {
    return this.service.artists(args);
  }

  @graphql.Query(() => Artist, { nullable: true })
  async artist(
    @graphql.Args() args: ArtistFindUniqueArgs
  ): Promise<Artist | null> {
    const result = await this.service.artist(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Artist)
  async createArtist(@graphql.Args() args: CreateArtistArgs): Promise<Artist> {
    return await this.service.createArtist({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Artist)
  async updateArtist(
    @graphql.Args() args: UpdateArtistArgs
  ): Promise<Artist | null> {
    try {
      return await this.service.updateArtist({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Artist)
  async deleteArtist(
    @graphql.Args() args: DeleteArtistArgs
  ): Promise<Artist | null> {
    try {
      return await this.service.deleteArtist(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Album], { name: "albums" })
  async findAlbums(
    @graphql.Parent() parent: Artist,
    @graphql.Args() args: AlbumFindManyArgs
  ): Promise<Album[]> {
    const results = await this.service.findAlbums(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Track], { name: "tracks" })
  async findTracks(
    @graphql.Parent() parent: Artist,
    @graphql.Args() args: TrackFindManyArgs
  ): Promise<Track[]> {
    const results = await this.service.findTracks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
